# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
     # - name: Download Octave
     #   run: Invoke-WebRequest https://ftp.gnu.org/gnu/octave/windows/octave-6.3.0-w64.7z -O octave-6.3.0-w64.7z


      # Runs a single command using the runners shell
      - name: Download test
        run: Invoke-WebRequest https://ftp.gnu.org/gnu/octave/windows/octave-6.3.0-w64.7z.sig -O octave-6.3.0-w64.7z.sig
      
      - name: list files
        run: dir
      
      #- name: Extract Octave
       # run: 7z x octave-6.3.0-w64.7z
        
      #- uses: actions/cache@v1
      #  with:
      #   path: octave-6.3.0-w64
      #   key: npm-packages
